package sedion.jeffli.wmuitp.entity;

// Generated 2014-4-17 18:23:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import java.util.TreeSet;

/**
 * Addressbook generated by hbm2java
 */
public class Addressbook implements java.io.Serializable {

	private Integer addressbookId;
	private String addressbookName;
	private String addressbookAbout;
	private String addressbookTime;
	private Set contacts = new HashSet(0);

	public Addressbook() {
	}

	public Addressbook(String addressbookName, String addressbookAbout,
			String addressbookTime, Set contacts) {
		this.addressbookName = addressbookName;
		this.addressbookAbout = addressbookAbout;
		this.addressbookTime = addressbookTime;
		this.contacts = contacts;
	}

	public Integer getAddressbookId() {
		return this.addressbookId;
	}

	public void setAddressbookId(Integer addressbookId) {
		this.addressbookId = addressbookId;
	}

	public String getAddressbookName() {
		return this.addressbookName;
	}

	public void setAddressbookName(String addressbookName) {
		this.addressbookName = addressbookName;
	}

	public String getAddressbookAbout() {
		return this.addressbookAbout;
	}

	public void setAddressbookAbout(String addressbookAbout) {
		this.addressbookAbout = addressbookAbout;
	}

	public String getAddressbookTime() {
		return this.addressbookTime;
	}

	public void setAddressbookTime(String addressbookTime) {
		this.addressbookTime = addressbookTime;
	}

	public Set getContacts() {
		return this.contacts;
	}

	public void setContacts(Set contacts) {
		this.contacts = contacts;
	}

	@Override
	public String toString()
	{
		return "Addressbook [addressbookId=" + addressbookId
				+ ", addressbookName=" + addressbookName
				+ ", addressbookAbout=" + addressbookAbout
				+ ", addressbookTime=" + addressbookTime + ", contacts="
				+ contacts + "]";
	}

	
}
